import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

// Which directory table each role's record lives in. business_associates
// gets its referral_code auto-generated by its own DB trigger on insert.
const ROLE_TABLE: Record<string, string> = {
  business: "business_associates",
  legal: "legal_team",
  technical: "technical_team",
  credit: "credit_team",
};

function json(body: unknown, status: number) {
  return new Response(JSON.stringify(body), { status, headers: { "Content-Type": "application/json" } });
}

Deno.serve(async (req: Request) => {
  if (req.method !== "POST") return json({ error: "Method not allowed" }, 405);
  try {
    const authHeader = req.headers.get("Authorization");
    if (!authHeader) return json({ error: "Unauthorized" }, 401);

    const url = Deno.env.get("SUPABASE_URL")!;
    const serviceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const admin = createClient(url, serviceKey);
    const token = authHeader.replace(/^Bearer\s+/i, "");

    const { data: callerData, error: callerError } = await admin.auth.getUser(token);
    if (callerError || !callerData.user) return json({ error: "Invalid session" }, 401);

    // FIX: authorize using the same source of truth the rest of the app
    // uses — public.users.role. The previous version checked the caller's
    // JWT app_metadata/user_metadata for a role, but nothing in this app
    // ever sets that, so this check failed for every real admin, including
    // the actual owner account.
    const { data: callerRow, error: callerRowError } = await admin
      .from("users")
      .select("role")
      .eq("auth_user_id", callerData.user.id)
      .maybeSingle();
    if (callerRowError || !callerRow || !["owner", "admin"].includes(callerRow.role)) {
      return json({ error: "Admin access required" }, 403);
    }

    const body = await req.json();
    const name = String(body.name || "").trim();
    const email = String(body.email || "").trim().toLowerCase();
    const phone = String(body.phone || "").trim();
    const role = String(body.role || "").trim();
    const password = String(body.password || "Password@123");

    const targetTable = ROLE_TABLE[role];
    if (!name || !email || !phone || !targetTable) {
      return json({ error: "name, email, phone and a valid role (business/legal/technical/credit) are required" }, 400);
    }

    // FIX: previously always checked/inserted into credit_team regardless
    // of the requested role, so a new Business Associate or Legal hire
    // silently ended up as a row in the Credit team's table instead.
    const { data: existingMember } = await admin.from(targetTable).select("id,email").eq("email", email).maybeSingle();
    const { data: existingUser } = await admin.from("users").select("id,email").eq("email", email).maybeSingle();
    if (existingMember || existingUser) {
      return json({ error: "Email already registered", existingMember, existingUser }, 409);
    }

    const { data: created, error: createError } = await admin.auth.admin.createUser({
      email,
      password,
      email_confirm: true,
      user_metadata: { name, phone, role },
    });
    if (createError || !created.user) {
      return json({ error: createError?.message || "Could not create auth user" }, 400);
    }
    const authUserId = created.user.id;

    // FIX: previously never inserted into public.users at all — this is
    // the table login() actually queries (by auth_user_id) to resolve the
    // signed-in user's role, so no account created by this function could
    // ever successfully log in, regardless of which directory table it
    // landed in.
    const { error: usersError } = await admin.from("users").insert({
      auth_user_id: authUserId,
      email,
      name,
      mobile: phone,
      role,
      status: "pending",
    });
    if (usersError) {
      await admin.auth.admin.deleteUser(authUserId);
      return json({ error: "Could not create users row: " + usersError.message }, 400);
    }

    // The role-specific directory table. Its own id column has no default
    // (the whole app supplies its own bigint id), so we generate one here
    // the same way the rest of the app does.
    const memberRow: Record<string, unknown> = {
      id: Date.now(),
      email,
      phone,
      status: "pending",
      auth_user_id: authUserId,
    };
    if (targetTable === "business_associates") {
      memberRow["NAME"] = name; // this table's name column is capitalized
    } else {
      memberRow["name"] = name;
    }

    const { data: member, error: insertError } = await admin.from(targetTable).insert(memberRow).select("*").single();
    if (insertError) {
      await admin.auth.admin.deleteUser(authUserId);
      await admin.from("users").delete().eq("auth_user_id", authUserId);
      return json({ error: `Could not create ${targetTable} row: ${insertError.message}` }, 400);
    }

    return json({ success: true, member, temporary_password: password }, 200);
  } catch (e) {
    return json({ error: e instanceof Error ? e.message : "Unexpected error" }, 500);
  }
});
